@startuml
Enum TiposBases{
SERVICIO
ADMINISTRATIVA
}
BaseCreador <|-down- BaseServicioCreador
BaseCreador <|-down- BaseAdministrativaCreador
Base <|-down- BaseServicio
Base <|-down- BaseAdministrativa
BaseServicioCreador ..> BaseServicio
BaseAdministrativaCreador ..> BaseAdministrativa

Escenario *--> GestorBases
GestorBases *--> BaseCreador

Escenario ..> TiposBases

Escenario ..> BaseServicioCreador
Escenario ..> BaseAdministrativaCreador
@enduml